In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px

from six.moves import urllib
import warnings
warnings.filterwarnings('ignore')

import os

In [2]:
data_dir = './data/'
os.makedirs(data_dir, exist_ok=True)
data_url = "https://raw.githubusercontent.com/mohitmahiyt/cardataset/refs/heads/main/cars_dataset.csv"

filename = os.path.basename(data_url)
print(f"downloading:{filename}")

filepath = os.path.join(data_dir, filename)
print(f"filepath:{filepath}")

urllib.request.urlretrieve(data_url, filepath)
print("file downloaded successfully")

downloading:cars_dataset.csv
filepath:./data/cars_dataset.csv
file downloaded successfully

In [3]:
df=pd.read_csv("./data/cars_dataset.csv")

In [4]:
df.head(20)

,car data set,NaN,NaN.1,NaN.2,NaN.3,NaN.4,NaN.5,NaN.6,NaN.7,NaN.8,NaN.9,NaN.10,NaN.11,NaN.12,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price,my_car
11,1.0,Maruti Alto,Maruti,Alto,9,53800,Dealer,CNG,Manual,26.83,796,38.4,5,235000,NaN
12,2.0,Maruti Alto,Maruti,Alto,11,11000,Dealer,CNG,Manual,26.83,796,38.4,5,185000,NaN
13,3.0,Maruti Alto,Maruti,Alto,11,80000,Dealer,CNG,Manual,26.83,796,38.4,5,150000,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,4.0,Maruti Alto,Maruti,Alto,10,57000,Dealer,CNG,Manual,26.83,796,38.4,5,172000,NaN
19,5.0,Maruti Alto,Maruti,Alto,11,72000,Individual,CNG,Manual,26.83,796,38.4,5,125000,NaN

In [5]:
df.describe()

       car data set
count  15411.000000
mean    9826.138213
std     5681.126720
min        1.000000
25%     4906.500000
50%     9872.000000
75%    14668.500000
max    30020.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15812 entries, 0 to 15811
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   car data set  15411 non-null  float64
 1   NaN           15412 non-null  object
 2   NaN.1         15412 non-null  object
 3   NaN.2         15412 non-null  object
 4   NaN.3         15412 non-null  object
 5   NaN.4         15412 non-null  object
 6   NaN.5         15412 non-null  object
 7   NaN.6         15412 non-null  object
 8   NaN.7         15412 non-null  object
 9   NaN.8         15412 non-null  object
 10  NaN.9         15412 non-null  object
 11  NaN.10        15412 non-null  object
 12  NaN.11        15412 non-null  object
 13  NaN.12        15412 non-null  object
 14  Unnamed: 14   1 non-null      object
dtypes: float64(1), object(14)
memory usage: 1.8+ MB

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
from six.moves import urllib
import matplotlib.pyplot as plt
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
import os

In [4]:
data_dir="./data/"
os.makedirs(data_dir,exist_ok=True)
data_url="https://raw.githubusercontent.com/mohitmahiyt/cardataset/refs/heads/main/cars_dataset.csv"

filename=os.path.basename(data_url)
print(f"downloading : {filename}")

filepath=os.path.join(data_dir,filename)
print(f"fileapth : {filepath}")

urllib.request.urlretrieve(data_url,filepath)
print("file downloaded successfully")

downloading : cars_dataset.csv
fileapth : ./data/cars_dataset.csv
file downloaded successfully

In [12]:
df=pd.read_csv("./data/cars_dataset.csv",header=11)

In [13]:
df.head(20)

,NaN,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price,my_car
0,1.0,Maruti Alto,Maruti,Alto,9.0,53800.0,Dealer,CNG,Manual,26.83,796.0,38.4,5.0,235000.0,NaN
1,2.0,Maruti Alto,Maruti,Alto,11.0,11000.0,Dealer,CNG,Manual,26.83,796.0,38.4,5.0,185000.0,NaN
2,3.0,Maruti Alto,Maruti,Alto,11.0,80000.0,Dealer,CNG,Manual,26.83,796.0,38.4,5.0,150000.0,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,4.0,Maruti Alto,Maruti,Alto,10.0,57000.0,Dealer,CNG,Manual,26.83,796.0,38.4,5.0,172000.0,NaN
8,5.0,Maruti Alto,Maruti,Alto,11.0,72000.0,Individual,CNG,Manual,26.83,796.0,38.4,5.0,125000.0,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,6.0,Maruti Alto,Maruti,Alto,5.0,42000.0,Dealer,CNG,Manual,33.44,796.0,40.3,4.0,260000.0,NaN
14,7.0,Maruti Alto,Maruti,Alto,7.0,28000.0,Dealer,CNG,Manual,33.44,796.0,40.3,4.0,281000.0,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,8.0,Maruti Alto,Maruti,Alto,3.0,29000.0,Dealer,CNG,Manual,33.44,796.0,40.3,4.0,345000.0,NaN

In [8]:
df.describe()

       car data set
count  15411.000000
mean    9826.138213
std     5681.126720
min        1.000000
25%     4906.500000
50%     9872.000000
75%    14668.500000
max    30020.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15812 entries, 0 to 15811
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   car data set  15411 non-null  float64
 1   NaN           15412 non-null  object
 2   NaN.1         15412 non-null  object
 3   NaN.2         15412 non-null  object
 4   NaN.3         15412 non-null  object
 5   NaN.4         15412 non-null  object
 6   NaN.5         15412 non-null  object
 7   NaN.6         15412 non-null  object
 8   NaN.7         15412 non-null  object
 9   NaN.8         15412 non-null  object
 10  NaN.9         15412 non-null  object
 11  NaN.10        15412 non-null  object
 12  NaN.11        15412 non-null  object
 13  NaN.12        15412 non-null  object
 14  Unnamed: 14   1 non-null      object
dtypes: float64(1), object(14)
memory usage: 1.8+ MB

In [18]:
df.drop(" my_car",axis=1,inplace=True)

In [19]:
df

,NaN,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,1.0,Maruti Alto,Maruti,Alto,9.0,53800.0,Dealer,CNG,Manual,26.83,796.0,38.4,5.0,235000.0
1,2.0,Maruti Alto,Maruti,Alto,11.0,11000.0,Dealer,CNG,Manual,26.83,796.0,38.4,5.0,185000.0
2,3.0,Maruti Alto,Maruti,Alto,11.0,80000.0,Dealer,CNG,Manual,26.83,796.0,38.4,5.0,150000.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15796,30016.0,Bentley Continental,Bentley,Continental,10.0,30000.0,Dealer,Petrol,Automatic,8.60,5998.0,552.0,4.0,8100000.0
15797,30017.0,Rolls-Royce Ghost,Rolls-Royce,Ghost,4.0,5000.0,Individual,Petrol,Automatic,10.20,6592.0,563.0,4.0,24200000.0
15798,30018.0,Bentley Continental,Bentley,Continental,9.0,37500.0,Dealer,Petrol,Automatic,6.00,5998.0,600.0,5.0,5200000.0
15799,30019.0,Ferrari GTC4Lusso,Ferrari,GTC4Lusso,2.0,3800.0,Dealer,Petrol,Automatic,4.00,3855.0,601.0,4.0,39500000.0
15800,30020.0,Bentley Continental,Bentley,Continental,9.0,9000.0,Dealer,Petrol,Automatic,9.50,5998.0,626.0,4.0,14500000.0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15801 entries, 0 to 15800
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   NaN                15411 non-null  float64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  float64
 5   km_driven          15411 non-null  float64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  float64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  float64
 13  selling_price      15411 non-null  float64
dtypes: float64(8), object(6)
memory usage: 1.7+ MB

In [27]:
df.isnull().sum()

NaN                  390
car_name             390
brand                390
model                390
vehicle_age          390
km_driven            390
seller_type          390
fuel_type            390
transmission_type    390
mileage              390
engine               390
max_power            390
seats                390
selling_price        390
dtype: int64

In [29]:
df[df.isna().all(axis=1)]

,NaN,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1046,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN